# Generated by Django 3.2.21 on 2023-09-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('preview', models.ImageField(upload_to='preview/')),
                ('video', models.FileField(upload_to='video/')),
            ],
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
